### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Phoscur** [antris/bacon-socket.io#1]
Using Bacon wrapping promises on angular clientside, I'd like to use Bacon on serverside too.
How can I use bacon-socket.io with authentication?

``` javascript
// works without bacon
  io.on('connection', socketioJwt.authorize({secret: config.tokenSecret, timeout: 15000}))
    .on('authenticated', function(socket) {
      console.log('socket authenticated', socket.decoded_token);
    });
```

``` javascript
// does not work and doesn't look proper..
var socketControl = baconSocketIo(io);
  socketControl.incomingSockets.map(socketioJwt.authorize({secret: config.tokenSecret, timeout: 15000}));
  socketControl.listenToAllSocketsOfType('authenticated', function (event) {
    var socket = event.socket;
    console.log('socket authenticated', socket.decoded_token);
    socket.on('chat.message', function (message) { // this should also have a nicer bacon way
      console.log('[broadcast] new chat message', message);
      io.sockets.emit('chat.message', message);
    });
```

Note: I'd like to be able to work with authenticated and non-authenticated sockets.

**Comment by antris** [comment]
This is more of a Bacon question rather than a `bacon-socket.io` question. Maybe you could try Stack Overflow? http://stackoverflow.com/tags/bacon.js/hot

Some things I noticed:
- You don't seem to have a side effect declared in the given example code. Bacon doesn't evaluate anything if there's no side effect declared (e.g. with `onValue`).
- On the line with the comment "this should also have a nicer bacon way", I think `flatMap` is what you are looking for.

I think it's best if you start from something simpler and go through some basic Bacon tutorials and then come back to your problem :) There's plenty of resources for learning Bacon and FRP.

Best
/Anton

**Comment by Phoscur** [comment]
I think it's an issue with this package. I still can't figure out how I would plug in the auth middleware. I have done things with Bacon, I guess I can just mix socket.io .on handlers and baconized streams..

**Comment by antris** [comment]
Have you gotten the auth middleware working on Bacon streams without `bacon-socket.io` library? Bacon EventStreams and Node Streams are different things and need to be wrapped before mixing :)

If you can post some working example (that I'm able to run) of how to reproduce a problem caused by `bacon-socket.io` then I'm glad to open a ticket. Until that I'll keep this one closed.

Best
/Anton
